apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "catalog-api.fullname" . }}
  labels:
    {{- include "catalog-api.labels" . | nindent 4 }}
    {{- with .Values.additionalDeploymentLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.deploymentAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  {{- if .Values.deploymentStrategy.enabled }}
  strategy:
    type: {{ .Values.deploymentStrategy.type }}
    {{- if eq .Values.deploymentStrategy.type "RollingUpdate" }}
    rollingUpdate:
      {{- toYaml .Values.deploymentStrategy.rollingUpdate | nindent 6 }}
    {{- end }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "catalog-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "catalog-api.selectorLabels" . | nindent 8 }}
        {{- with .Values.additionalPodLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "catalog-api.serviceAccountName" . }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: catalog-api
          image: "{{ .Values.containerImage.repository }}:{{ .Values.containerImage.tag }}"
          imagePullPolicy: {{ .Values.containerImage.pullPolicy }}
          ports:
            {{- range $name, $port := .Values.containerPorts }}
            {{- if not $port.disabled }}
            - name: {{ $name }}
              containerPort: {{ $port.port }}
              protocol: {{ $port.protocol }}
            {{- end }}
            {{- end }}
          env:
            - name: PORT
              value: {{ index .Values.containerPorts.http "port" | quote }}
            {{- range $k, $v := .Values.envVars }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- with .Values.startupProbe }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.containerResources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- if or .Values.emptyDirs (gt (int .Values.shutdownDelay) 0) }}
          volumeMounts:
            {{- range $name, $path := .Values.emptyDirs }}
            - name: {{ $name }}
              mountPath: {{ $path }}
            {{- end }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "sleep {{ .Values.shutdownDelay }}"]
          {{- end }}
      volumes:
        {{- range $name, $_ := .Values.emptyDirs }}
        - name: {{ $name }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
